import type { Metadata } from "next";
import "./globals.css";
import PriceProvider from "@/context/contextPrice";
import LangProvider from "@/context/contexLang";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LangProvider>
          <PriceProvider>{children}</PriceProvider>
        </LangProvider>
      </body>
    </html>
  );
}
